<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <RootNamespace>Logic</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="itext" Version="9.1.0" />
    <PackageReference Include="itext.bouncy-castle-adapter" Version="9.1.0" />
    <PackageReference Include="PdfSharpCore" Version="1.3.65" />
    <PackageReference Include="SkiaSharp" Version="3.116.1" />
  </ItemGroup>

</Project> 